coverage:
  round: down
  precision: 2
  status:
    patch: false
    project:
      default:
        threshold: 2%
        flags:
          - tests_ci
        target: auto
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null
flags:
  tests:
    carryforward: true
ignore:
- "Tests"
