name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: set -o pipefail && xcodebuild test -scheme TraktSwift -enableCodeCoverage YES "OTHER_SWIFT_FLAGS=-D TESTING"
      env:
          TESTS_TRAKT_STAGING_CLIENT_ID: ${{ secrets.TESTS_TRAKT_STAGING_CLIENT_ID }}
    - uses: codecov/codecov-action@v1
      name: CodeCov export
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
